### ISSUE TITLE
NoSuchElementException is thrown for some weird sentences

### ISSUE THREAD

**Issue by asher-stern** [Noahs-ARK/semafor#31]
```
Exception in thread "main" java.util.NoSuchElementException
	at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
	at edu.cmu.cs.lti.ark.fn.utils.DataPoint.buildParsesForLine(DataPoint.java:171)
	at edu.cmu.cs.lti.ark.fn.utils.DataPointWithFrameElements.<init>(DataPointWithFrameElements.java:86)
	at edu.cmu.cs.lti.ark.fn.parsing.DataPrep.load(DataPrep.java:176)
	at edu.cmu.cs.lti.ark.fn.parsing.DataPrep.<init>(DataPrep.java:103)
	at edu.cmu.cs.lti.ark.fn.parsing.CreateAlphabet.getDataPoints(CreateAlphabet.java:124)
	at edu.cmu.cs.lti.ark.fn.parsing.CreateAlphabet.run(CreateAlphabet.java:76)
	at edu.cmu.cs.lti.ark.fn.parsing.ParserDriver.identifyArguments(ParserDriver.java:307)
	at edu.cmu.cs.lti.ark.fn.parsing.ParserDriver.runParser(ParserDriver.java:238)
	at edu.cmu.cs.lti.ark.fn.parsing.ParserDriver.main(ParserDriver.java:108)
```

This happens for the attached file, whose contents are merely:
```
| origin = 
```

When running `bin/fnParserDriverMalt.sh` (specifying xml format)

[failure.txt](https://github.com/Noahs-ARK/semafor/files/1111589/failure.txt)

**Comment by asher-stern** [comment]
In version v3.0-alpha-04
